buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = project.mod_version
group = project.mod_group
archivesBaseName = project.mod_id

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "${minecraft_version}-${forge_version}"
    runDir = 'run'
    mappings = mappings_version
    makeObfSourceJar = false
}

repositories {
    maven { url = 'https://maven.minecraftforge.net' }
    mavenCentral()
}

dependencies {
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', project.minecraft_version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand(
                'version': project.version,
                'mcversion': project.minecraft_version,
                'modid': project.mod_id,
                'modname': project.mod_name,
                'author': project.mod_author
        )
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
